server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    username: root
    password: 90813
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "XUpMx029oxHnQ1nvsWR/MTnHmfHLTLvDXsYLOb7Hepy+7zTpzFxTPXa2VzgpzuTd"